version: '3.8'

services:

  # fake server
  fake-server:
    build:
      context: server/
    environment:
      JAEGER_ENDPOINT: 'http://jaeger-all-in-one:14268/api/traces'
    expose:
      - "8080"
    ports:
      - "8080:8080"

  # jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.33
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16685:16685" # jaeger-query & ui
      - "16686:16686" # jaeger-query & ui
      - "14268:14268"
      - "14250:14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.49.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./conf/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one

  # haproxy
  haproxy-1:
    image: haproxy:2.5.6-alpine
    depends_on:
      - haproxy-2
    environment:
      SERVICE_NAME: haproxy-1
      FRONTEND_PORT_WITH_SPOA: 7001
      FRONTEND_PORT_WITHOUT_SPOA: 8001
      BACKEND_ADDRESS: "haproxy-2:7002"
    volumes:
      - ./conf/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./conf/spoe.cfg:/usr/local/etc/haproxy/spoe.cfg
    ports:
      - "7001:7001"
      - "8001:8001"

  # haproxy
  haproxy-2:
    image: haproxy:2.5.6-alpine
    depends_on:
      - fake-server
    environment:
      SERVICE_NAME: haproxy-2
      FRONTEND_PORT_WITH_SPOA: 7002
      FRONTEND_PORT_WITHOUT_SPOA: 8002
      BACKEND_ADDRESS: "fake-server:8080"
    volumes:
      - ./conf/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./conf/spoe.cfg:/usr/local/etc/haproxy/spoe.cfg
    ports:
      - "7002:7002"
      - "8002:8002"
