version: '3.8'

services:

  # fake server
  fake-server:
    build:
      context: server/
    ports:
      - "8080:8080"

  # jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.33
    ports:
     # - "5775:5775/udp"
     # - "6831:6831/udp"
     # - "6832:6832/udp"
     # - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.49.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./conf/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one

  # haproxy
  haproxy:
    image: haproxy:2.5.6-alpine
    volumes:
      - ./conf/haproxy.cfg:/etc/haproxy/haproxy.conf
      - 
  docker run --rm --name haproxy-spoa-example -v $(pwd)/haproxy_conf:/usr/local/etc/haproxy -v $(pwd)/haproxy_run:/var/run -e FE_BIND=unix@/var/run/haproxy.sock --network host haproxy:2.2-rc-alpine haproxy -f /usr/local/etc/haproxy/haproxy.cfg -d -V

